# Generated by Django 4.1.3 on 2022-11-05 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_customeraddress_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='order',
            new_name='customer',
        ),
    ]
